application:
  name: node_buildozer
  project: node_buildozer
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: node_buildozer
    paths:
    - /*
