version: "3"
services:
  backend:
    image: node:alpine
    # volumes:
    #   - ./:/app
    # working_dir: /app
    ports:
      - 8080
    command: npm run watch:dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
    # volumes:
    #   - ./data/db:/data/db
