version: 2
jobs:
  build:
    working_directory: ~/projects
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm packages
          command: npm install
      - save_cache:
          key: v-1dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_FINGERPRINT
      - deploy:
          name: Deploy to Heroku if tests pass and branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD
            fi